/**
 * Export flags to various formats
 */
import { FlagDefinition, FlagManifest, ExportFormat, EvaluationContext } from './types';
import { toYaml, toJson } from './parser';
import { evaluateFlag } from './evaluator';

/**
 * Export flags to specified format
 */
export function exportFlags(
  manifest: FlagManifest,
  format: ExportFormat,
  context?: EvaluationContext
): string {
  switch (format) {
    case 'yaml':
      return toYaml(manifest);
    case 'json':
      return toJson(manifest);
    case 'env':
      return toEnvFormat(manifest, context);
    case 'csv':
      return toCsvFormat(manifest);
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

/**
 * Export as .env file format
 */
export function toEnvFormat(manifest: FlagManifest, context?: EvaluationContext): string {
  const prefix = manifest.namespace ? `${manifest.namespace.toUpperCase()}_` : 'FLAG_';
  const lines: string[] = [
    `# flagops export - ${new Date().toISOString()}`,
    `# Environment: ${context?.environment || 'default'}`,
    '',
  ];

  for (const flag of manifest.flags) {
    const result = evaluateFlag(flag, context);
    const envName = `${prefix}${flag.name.toUpperCase().replace(/[.-]/g, '_')}`;
    const value = typeof result.value === 'boolean' ? (result.value ? '1' : '0') : String(result.value);
    if (flag.description) {
      lines.push(`# ${flag.description}`);
    }
    lines.push(`${envName}=${value}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Export as CSV format
 */
export function toCsvFormat(manifest: FlagManifest): string {
  const headers = ['name', 'status', 'type', 'defaultValue', 'description', 'owner', 'tags', 'createdAt', 'updatedAt'];
  const lines = [headers.join(',')];

  for (const flag of manifest.flags) {
    const row = [
      csvEscape(flag.name),
      csvEscape(flag.status),
      csvEscape(flag.type),
      csvEscape(String(flag.defaultValue)),
      csvEscape(flag.description || ''),
      csvEscape(flag.owner || ''),
      csvEscape(flag.tags?.join(';') || ''),
      csvEscape(flag.createdAt),
      csvEscape(flag.updatedAt),
    ];
    lines.push(row.join(','));
  }

  return lines.join('\n') + '\n';
}

function csvEscape(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

/**
 * Generate a TypeScript type definition for flags
 */
export function generateTypeDefinition(manifest: FlagManifest): string {
  const lines = [
    '// Auto-generated by flagops',
    '// Do not edit manually',
    '',
    'export interface FlagOpsFlags {',
  ];

  for (const flag of manifest.flags) {
    const tsType = flagTypeToTs(flag);
    if (flag.description) {
      lines.push(`  /** ${flag.description} */`);
    }
    lines.push(`  '${flag.name}': ${tsType};`);
  }

  lines.push('}');
  lines.push('');
  lines.push(`export type FlagName = keyof FlagOpsFlags;`);
  lines.push('');

  return lines.join('\n');
}

function flagTypeToTs(flag: FlagDefinition): string {
  switch (flag.type) {
    case 'boolean': return 'boolean';
    case 'string': return 'string';
    case 'number': return 'number';
    case 'multivariate': return 'string | string[]';
    default: return 'unknown';
  }
}
